[package]
name = "alloc_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default=["page_map_debug"]
page_map_debug=[]

[dependencies]
libc = "0.2.153"
x86_64 = { version = "0.14.11",default-features = false,features = ["instructions"] }
rand = {version = "0.8.5",features = ["small_rng"]}
ahash = { version = "0.8.7" ,default-features = false}
modular-bitfield = "0.11.2"
tikv-jemallocator ="0.5.4"
static_assertions = "1.1.0"